# Generated by Django 4.1.5 on 2023-07-17 14:11

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descriptions"
                    ),
                ),
                (
                    "preview_text",
                    models.TextField(blank=True, max_length=120, null=True),
                ),
                (
                    "visibility_status",
                    models.CharField(
                        choices=[("d", "draft"), ("p", "published"), ("a", "archived")],
                        default="d",
                        max_length=1,
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default="0", max_digits=6),
                ),
                ("minimum_participants", models.PositiveSmallIntegerField(default=2)),
                ("maximum_participants", models.PositiveSmallIntegerField(default=16)),
            ],
        ),
    ]
