# Generated by Django 5.2.4 on 2025-07-31 09:39

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriptions')),
                ('preview_text', models.TextField(blank=True, max_length=180, null=True)),
                ('visibility_status', models.CharField(choices=[('a', 'archived'), ('d', 'draft'), ('p', 'published')], default='d', max_length=1)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=6)),
                ('minimum_participants', models.PositiveSmallIntegerField(default=2)),
                ('maximum_participants', models.PositiveSmallIntegerField(default=16)),
            ],
        ),
    ]
