# Generated by Django 4.1.5 on 2023-07-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="preview_text",
            field=models.TextField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="visibility_status",
            field=models.CharField(
                choices=[("p", "published"), ("a", "archived"), ("d", "draft")],
                default="d",
                max_length=1,
            ),
        ),
    ]
