on:
  push:
    branches:
      - 'old-html-site/Main'

jobs:
  deploy:
    name: Checkout and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy
        uses: cinderblockgames/ftp-action@v1.2.2
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password:  ${{ secrets.FTP_PASSWORD }}
          source: ./
          destination: /customers/4/a/0/cfspmx0u3/webroots/sites/webspace/httpdocs/vanpallethout.nl
          skipUnchanged: true
          skipDirectories: .github|.git
