on:
  push:
    branches:
      - 'old-html-site/Main'

jobs:
  deploy:
    name: Checkout and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy
        uses: priradev/ftp-interactions@v0.2.9-beta
        with:
          host: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password:  ${{ secrets.FTP_PASSWORD }}
<<<<<<< HEAD
          verify_cert: false
          local_dir: ./
          remote_dir: /customers/4/a/0/cfspmx0u3/webroots/sites/webspace/httpdocs/vanpallethout.nl 
          create_remote_dir: false
=======
          local_dir: ./
          remote_dir: /customers/4/a/0/cfspmx0u3/webroots/sites/webspace/httpdocs/vanpallethout.nl 
>>>>>>> 8c3c50878fa8f7e8409bedcc1974eca5487adce4
