# Generated by Django 5.2.4 on 2025-07-31 09:39

import django.db.models.deletion
import django_extensions.db.fields
import pathlib
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Model name')),
                ('hex_code', models.CharField(max_length=7, unique=True, validators=[products.validators.validate_hex_code], verbose_name='Color hex code')),
                ('paint_type', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Material name')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriptions')),
                ('visibility_status', models.CharField(choices=[('a', 'archived'), ('d', 'draft'), ('p', 'published')], default='d', max_length=1)),
                ('dimensions', models.CharField(blank=True, help_text='Please use the following format: <em>Width x Length x Height</em>.', max_length=40, null=True)),
                ('dimensions_seat', models.CharField(blank=True, help_text='Please use the following format: <em>Width x Length x Height</em>.', max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriptions')),
                ('visibility_status', models.CharField(choices=[('a', 'archived'), ('d', 'draft'), ('p', 'published')], default='d', max_length=1)),
                ('available', models.CharField(choices=[('a', 'available'), ('so', 'sold out'), ('r', 'on request')], default='a', max_length=2)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=6)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('image_folder', models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path=pathlib.PureWindowsPath('C:/Users/Johannes/Documents/Code/van-pallethout/static/media/images'))),
                ('colors', models.ManyToManyField(blank=True, to='products.color')),
                ('material', models.ManyToManyField(blank=True, to='products.material')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='model',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.type'),
        ),
    ]
