# Generated by Django 4.1.5 on 2023-01-10 11:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "hex_code",
                    models.CharField(
                        max_length=7,
                        unique=True,
                        validators=[products.validators.validate_hex_code],
                    ),
                ),
                ("paint_type", models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("description", models.TextField(null=True)),
                (
                    "visibility_status",
                    models.CharField(
                        choices=[("d", "draft"), ("a", "archived"), ("p", "published")],
                        default="draft",
                        max_length=1,
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        help_text="Please use the following format: <em>Width x Length x Height</em>.",
                        max_length=40,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("description", models.TextField(null=True)),
                (
                    "visibility_status",
                    models.CharField(
                        choices=[("d", "draft"), ("a", "archived"), ("p", "published")],
                        default="draft",
                        max_length=1,
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        help_text="Please use the following format: <em>Width x Length x Height</em>.",
                        max_length=40,
                        null=True,
                    ),
                ),
                ("colors", models.ManyToManyField(to="products.color")),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.model",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="model",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.type",
            ),
        ),
    ]
