# Generated by Django 4.1.5 on 2023-01-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
        migrations.AlterField(
            model_name="color",
            name="paint_type",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="dimensions",
            field=models.CharField(
                blank=True,
                help_text="Please use the following format: <em>Width x Length x Height</em>.",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.type",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="visibility_status",
            field=models.CharField(
                choices=[("p", "published"), ("d", "draft"), ("a", "archived")],
                default="draft",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.model",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="visibility_status",
            field=models.CharField(
                choices=[("p", "published"), ("d", "draft"), ("a", "archived")],
                default="draft",
                max_length=1,
            ),
        ),
    ]
