# Generated by Django 4.1.5 on 2023-01-10 12:46

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
        migrations.AddField(
            model_name="model",
            name="dimensions_seat",
            field=models.CharField(
                blank=True,
                help_text="Please use the following format: <em>Width x Length x Height</em>.",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.CharField(
                choices=[("r", "on request"), ("so", "sold out"), ("a", "available")],
                default="a",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="available_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_folder",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                blank=True,
                null=True,
                path=pathlib.PurePosixPath(
                    "/Users/johannes/Documents/code/github/vanpallethout-website/static/images"
                ),
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=6),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PurePosixPath(
                    "/Users/johannes/Documents/code/github/vanpallethout-website/static/images/thumbnails"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="paint_type",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="dimensions",
            field=models.CharField(
                blank=True,
                help_text="Please use the following format: <em>Width x Length x Height</em>.",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.type",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="visibility_status",
            field=models.CharField(
                choices=[("a", "archived"), ("p", "published"), ("d", "draft")],
                default="d",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.model",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="visibility_status",
            field=models.CharField(
                choices=[("a", "archived"), ("p", "published"), ("d", "draft")],
                default="d",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.ManyToManyField(to="products.material"),
        ),
    ]
