# Generated by Django 4.1.5 on 2023-01-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visibility_status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'draft'), ('a', 'archived')], default='draft', max_length=1),
        ),
    ]
