# Generated by Django 4.1.5 on 2023-01-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_material_remove_product_dimensions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.CharField(
                choices=[("so", "sold out"), ("r", "on request"), ("a", "available")],
                default="a",
                max_length=2,
            ),
        ),
    ]
