# Generated by Django 4.1.5 on 2023-01-09 15:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_visibility_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(null=True)),
                ('visibility_status', models.CharField(choices=[('p', 'published'), ('d', 'draft'), ('a', 'archived')], default='draft', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.model'),
        ),
    ]
