# Generated by Django 4.1.5 on 2023-01-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.CharField(
                choices=[("a", "available"), ("so", "sold out"), ("r", "on request")],
                default="a",
                max_length=2,
            ),
        ),
    ]
