# Generated by Django 4.1.5 on 2023-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_model_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='visibility_status',
            field=models.CharField(choices=[('a', 'archived'), ('d', 'draft'), ('p', 'published')], default='draft', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='visibility_status',
            field=models.CharField(choices=[('a', 'archived'), ('d', 'draft'), ('p', 'published')], default='draft', max_length=1),
        ),
    ]
