# Generated by Django 4.1.5 on 2023-01-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="visibility_status",
            field=models.CharField(
                choices=[("d", "draft"), ("a", "archived"), ("p", "published")],
                default="d",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.CharField(
                choices=[("so", "sold out"), ("a", "available"), ("r", "on request")],
                default="a",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="visibility_status",
            field=models.CharField(
                choices=[("d", "draft"), ("a", "archived"), ("p", "published")],
                default="d",
                max_length=1,
            ),
        ),
    ]
