# Generated by Django 4.1.5 on 2023-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_model_visibility_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="visibility_status",
            field=models.CharField(
                choices=[("d", "draft"), ("a", "archived"), ("p", "published")],
                default="d",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(to="products.color"),
        ),
        migrations.AlterField(
            model_name="product",
            name="material",
            field=models.ManyToManyField(to="products.material"),
        ),
        migrations.AlterField(
            model_name="product",
            name="visibility_status",
            field=models.CharField(
                choices=[("d", "draft"), ("a", "archived"), ("p", "published")],
                default="d",
                max_length=1,
            ),
        ),
    ]
