# Generated by Django 4.1.5 on 2023-01-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0008_alter_model_visibility_status_alter_product_colors_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="visibility_status",
            field=models.CharField(
                choices=[("a", "archived"), ("p", "published"), ("d", "draft")],
                default="d",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.CharField(
                choices=[("r", "on request"), ("a", "available"), ("so", "sold out")],
                default="a",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(blank=True, to="products.color"),
        ),
        migrations.AlterField(
            model_name="product",
            name="material",
            field=models.ManyToManyField(blank=True, to="products.material"),
        ),
        migrations.AlterField(
            model_name="product",
            name="visibility_status",
            field=models.CharField(
                choices=[("a", "archived"), ("p", "published"), ("d", "draft")],
                default="d",
                max_length=1,
            ),
        ),
    ]
