# Generated by Django 4.1.5 on 2023-01-10 13:57

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_model_visibility_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="hex_code",
            field=models.CharField(
                max_length=7,
                unique=True,
                validators=[products.validators.validate_hex_code],
                verbose_name="Color hex code",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="Model name"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="Material name"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descriptions"),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.CharField(
                choices=[("so", "sold out"), ("r", "on request"), ("a", "available")],
                default="a",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descriptions"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="Name"),
        ),
    ]
