# Generated by Django 4.1.5 on 2023-01-10 14:57

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_color_hex_code_alter_color_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="visibility_status",
            field=models.CharField(
                choices=[("d", "draft"), ("p", "published"), ("a", "archived")],
                default="d",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_folder",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                blank=True,
                null=True,
                path=pathlib.PurePosixPath(
                    "/Users/johannes/Documents/code/github/vanpallethout-website/static/media/images"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PurePosixPath(
                    "/Users/johannes/Documents/code/github/vanpallethout-website/static/media/images/thumbnails"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="visibility_status",
            field=models.CharField(
                choices=[("d", "draft"), ("p", "published"), ("a", "archived")],
                default="d",
                max_length=1,
            ),
        ),
    ]
