# Generated by Django 4.1.5 on 2023-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_model_visibility_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="visibility_status",
            field=models.CharField(
                choices=[("p", "published"), ("a", "archived"), ("d", "draft")],
                default="d",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.CharField(
                choices=[("so", "sold out"), ("a", "available"), ("r", "on request")],
                default="a",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="visibility_status",
            field=models.CharField(
                choices=[("p", "published"), ("a", "archived"), ("d", "draft")],
                default="d",
                max_length=1,
            ),
        ),
    ]
