# Generated by Django 4.1.5 on 2023-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_model_visibility_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="visibility_status",
            field=models.CharField(
                choices=[("d", "draft"), ("p", "published"), ("a", "archived")],
                default="d",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.CharField(
                choices=[("a", "available"), ("so", "sold out"), ("r", "on request")],
                default="a",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="visibility_status",
            field=models.CharField(
                choices=[("d", "draft"), ("p", "published"), ("a", "archived")],
                default="d",
                max_length=1,
            ),
        ),
    ]
